grails-app/domain/cgi/Wav.groovy
package cgi

import java.time.LocalDateTime

class Wav {

    //Failinimi
    String fileName;
    //Faili baidid
    byte[] fileBytes;
    //Faili sisu näidis
    String contentPreview

    //Faili (algne) salvestamise aeg
    LocalDateTime time;

    //Lubame suuremat faili lisada
    //https://guides.grails.org/grails-upload-file/guide/index.html ,punkt 4.1
    //"	Images may be big files; we use the mapping closure to configure the sqlType" - longblobi kohta

    static constraints = {
        fileBytes column: 'file_bytes', sqlType: 'longblob'
    }
}

grails-app/controllers/cgi/UrlMappings.groovy
package cgi

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/controllers/cgi/WavController.groovy
package cgi

import festival.FestivalClient
import sun.audio.AudioData
import sun.audio.AudioDataStream
import sun.audio.AudioPlayer

import java.nio.charset.Charset
import java.time.LocalDateTime

import static org.springframework.http.HttpStatus.*

class WavController {
    //Määrame serveri ja pordi ning loome ühenduse festivali appiga
    String server = "localhost";
    int port = 1314;


    WavService wavService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    //index leht
    def index(Integer max) {
        List<Wav> files;

        //Salvestame failide listi muutujasse wavsList. Viimasena loodud objekt salvestatakse ka muutujasse recentFile,
        // kui see eksisteerib.
        if (Wav.list().size() > 0)
            files = Wav.list(sort:'time', order: 'desc')

        if (files != null && files.size() >= 1)
            [wavsList: files, recentFile: files.get(0)]
        else
            [wavsList: Arrays.asList(), recentFile: Arrays.asList()]

    }

    //Faili salvestamine
    def save(String wav) {
        //Loome uue Wav domain objekti
        Wav w = new Wav()

        //Valime esimesed (kuni) 200 tähte kirjelduseks
        wav.length() < 200 ? (w.contentPreview = wav) : (w.contentPreview = wav.substring(0, 100))

        //Loome festivali rakenduse kaudu faili sisu ning salvestame faili
        try {
            FestivalClient fc = new FestivalClient(server, port);

            //Muudame kodeeringu UTF-8 pealt ISO-8859-15 peale, et kõik tähed oleks 1-baidised
            // festival on vana app ja ei tööta mitmebaidiste tähtedega
            //ISO...-15 on versioon, mille puhul on eesti keele tähtede kodeering lõpule viidud.(Wikipedia)
            // https://www.web3.lu/character-encoding-for-festival-tts-files/
            byte[] bytes = wav.getBytes(Charset.forName("UTF-8"));
            wav = new String(bytes, Charset.forName("ISO-8859-15"));

            //Stringi teisendamine .wav failiks
            byte[] waveBytes = fc.StringToWave(wav);

            //Lisame baidid ja faili nime(datetime) meie wav objektile ning salvestame
            w.fileBytes = waveBytes;
            w.fileName = LocalDateTime.now().toString();
            w.time = LocalDateTime.now()

            w.save()
            wavService.save(w)

            //teade audiofaili loomise õnnestumisest
            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'w.id', default: 'Wav'), w.fileName])
                }
                '*'{ respond wav, [status: OK] }
            }

            //teade ebaõnnestumisst
        } catch (Exception e) {
            flash.message = "Invalid input"
        }
        finally {
            redirect action: 'index'
        }

    }

    //Loeme baidid andmebaasist sisse ja esitame selle
    def playWav() {
        try
        {
            //Võtame objekti id järgi
            Wav el = wavService.get(Long.parseLong(params.id))

            // Loome AudioData(Stream) objekti baitide arrayst
            AudioData audiodata = new AudioData(el.fileBytes);
            AudioDataStream audioStream = new AudioDataStream(audiodata);
            // Mängime heli AudioPlayeriga
            AudioPlayer.player.start(audioStream);

        }
        catch (Exception exc)
        {
            flash.message = 'File playback error'
        }
        finally {

            redirect action: "index"
        }
    }

    def download() {


        try {
            //Võtame andmebaasist elemendi id järgi
            Wav el = wavService.get(Long.parseLong(params.id))

            //Sain abi https://stackoverflow.com/questions/6109859/grails-download-file/22679796
            // ja http://grails-dev.blogspot.com/2013/07/file-upload-functionality-2-download.html
            //Määrame tüübi, pikkuse ja headeri
            response.contentType = "application/octet-stream"
            response.contentLength = el.fileBytes.length
            response.setHeader("Content-disposition", "attachment;filename=\"${el.fileName}.wav\"")

            //Kirjutame/laeme faili alla
            response.outputStream.write(el.fileBytes)
        } catch (Exception e) {
            flash.message = 'Error while downloading file'
        }
        //Ei pea index lehele suunama kasutades ainult response'i
    }


    //Faili esitamine, ilma salvestamata
    def preview(String wav) {

        try {
            if (wav == null || wav.matches(" *"))
                throw new UnsupportedOperationException("Input must contain characters.")

            FestivalClient fc = new FestivalClient(server, port);

            //Muudame kodeeringu UTF-8 pealt ISO-8859-15 peale, et kõik tähed oleks 1-baidised
            // festival on vana app ja ei tööta mitmebaidiste tähtedega
            // https://www.web3.lu/character-encoding-for-festival-tts-files/
            byte[] bytes = wav.getBytes(Charset.forName("UTF-8"));
            wav = new String(bytes, Charset.forName("ISO-8859-15"));

            byte[] waveBytes = fc.StringToWave(wav);

            //Esitame audio
            AudioData audiodata = new AudioData(waveBytes);
            AudioDataStream audioStream = new AudioDataStream(audiodata);
            AudioPlayer.player.start(audioStream);

        } catch (Exception e) {
            flash.message = 'Preview not playable'
            println e.message
        }
        finally {
            redirect action: 'index'
        }
    }

    //Faili nime muutmine
    def edit(String newFileName) {
        try {
            //kontrollime ega siestatud sõne ei koosne ainult tühikust(tühi sõne kaasa arvatud)
            if (newFileName.matches(" *"))
                throw new UnsupportedOperationException("Input must contain characters.");
            //Saame andmebaasist objekti id kaudu, määrame uue failinime ja salvestame selle
            Wav el = wavService.get(Long.parseLong(params.id))
            el.fileName = newFileName
            el.save()
            wavService.save(el)

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'el.id', default: 'Wav'), el.fileName])
                }
                '*'{ respond wav, [status: OK] }
            }

        } catch (Exception e) {
            flash.message = 'Error changing file name'
            println e.message
        }
        finally {
            redirect action: 'index'
        }
    }

}

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top" role="navigation">
    <a class="navbar-brand" href="/#"><asset:image src="grails.svg" alt="Grails Logo"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" aria-expanded="false" style="height: 0.8px;" id="navbarContent">
        <ul class="nav navbar-nav ml-auto">
            <g:pageProperty name="page.nav"/>
        </ul>
    </div>

</nav>

<g:layoutBody/>


<div id="spinner" class="spinner" style="display:none;">
    <g:message code="spinner.alt" default="Loading&hellip;"/>
</div>

<asset:javascript src="application.js"/>

</body>
</html>

grails-app/views/wav/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'wav.label', default: 'Wav')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-wav" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-wav" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.wav}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.wav}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.wav}" method="POST">
                    <textarea bean="wav"/></textarea>
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            </g:form>
        </div>
    </body>
</html>

grails-app/views/wav/index.gsp
<!DOCTYPE html>
<html>

    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'wav.label', default: 'Wav')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-wav" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/wav')}"><g:message code="default.home.label"/></a></li>
            </ul>
        </div>
            <g:form resource="${this.wav}" method="POST">
                <div class="row">
                <g:textArea class="form-control" name="wav" id="wav" style="width: 50%" required="true"></g:textArea>
                <g:actionSubmit class="update" action="save" value="Generate wave" />
                <g:actionSubmit class="update" action="preview" value="Preview" />
                </div>
            </g:form>

            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>

            <div id="recent_file">
                <h1>Recent file</h1>
                <table class="table-hover table-bordered">
                    <thead>
                        <th>File name(time of generation)</th>
                        <th>Content preview</th>
                    </thead>
                    <tbody>
                        <tr>
                            <g:each in="${recentFile}" var="recent">
                                <td>
                                    ${recent.fileName}
                                </td>
                                <td>
                                    ${recent.contentPreview}
                                </td>
                                <td>
                                    <g:link controller="wav" action="playWav" params="[value: 'recentFile.value']" id="${recentFile.id}">
                                        <button id="${recent.id.toString()}_play" class="btn btn-primary">Play</button>
                                    </g:link>
                                </td>
                                <td>
                                    <g:link controller="wav" action="download" params="[value: 'recentFile.value']" id="${recentFile.id}">
                                        <button class="btn btn-primary">Download</button>
                                    </g:link>
                                </td>
                                <td>
                                    <g:form resource="${this.wav}" method="POST" id="${recentFile.id}">
                                        <div class="row">
                                            <g:textField class="form-control" name="newFileName" id="newFileName" required="true" style="width: auto"></g:textField>
                                            <g:actionSubmit class="btn btn-primary" action="edit" value="Edit file name" />
                                        </div>
                                    </g:form>
                                </td>
                            </g:each>
                        </tr>
                    </tbody>
                </table>
            </div>

%{--            <f:table collection="${wavList}" />--}%
            <table class="table-hover table-bordered">
                <h1>All .wav files</h1>
                <input class="form-control" id="filter" type="text" placeholder="Search..">

                <thead>
                    <th scope="col">File name</th>
                    <th scope="col">Content preview</th>
                </thead>
                <tbody id="wav_table">
                    <g:each in="${wavsList}" var="p">
                            <tr>
                                <td>${p.fileName}</td>
                                <td>${p.contentPreview}</td>

                                <td>
                                    <g:link controller="wav" action="playWav" params="[value: 'p.value']" id="${p.id}">
                                        <button id="${p.id.toString()}_play" class="btn btn-primary">Play</button>
                                    </g:link>
                                </td>
                                <td>
                                    <g:link controller="wav" action="download" params="[value: 'p.value']" id="${p.id}">
                                        <button class="btn btn-primary">Download</button>
                                    </g:link>
                                </td>
                                <td>
                                    <g:form resource="${this.wav}" method="POST" id="${p.id}">
                                        <div class="row">
                                            <g:textField class="form-control" name="newFileName" id="newFileName" required="true" style="width: auto"></g:textField>
                                            <g:actionSubmit class="btn btn-primary" action="edit" value="Edit file name" />
                                        </div>
                                    </g:form>
                                </td>
                            </tr>
                    </g:each>
                </tbody>
            </table>


            <div class="pagination">
                <g:paginate total="${wavCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/wav/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'wav.label', default: 'Wav')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-wav" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-wav" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="wav" />
            <g:form resource="${this.wav}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.wav}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>